name: build-x86-64-immortalwrt-24.10

on:
  workflow_dispatch:
    inputs:
      partsize:
        description: '请输入要编译固件大小(单位MB)'
        required: true
        default: '1024'
      include_docker:
        description: '是否编译Docker插件'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      include_others:
        description: '是否编译拓展插件'
        required: true
        default: 'yes'
        type: choice
        options:
          - 'yes'
          - 'no'
      enable_pppoe:
        description: "是否配置PPPoE拨号信息?"
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'
      pppoe_account:
        description: "宽带账号 (若启用PPPoE)"
        required: false
      pppoe_password:
        description: "宽带密码 (若启用PPPoE)"
        required: false

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set executable permissions
        run: chmod +x ${{ github.workspace }}/x86-64/build.sh

      - name: Validate PPPoE Inputs
        run: |
          if [[ "${{ github.event.inputs.enable_pppoe }}" == "yes" ]]; then
            if [[ -z "${{ inputs.pppoe_account }}" || -z "${{ inputs.pppoe_password }}" ]]; then
              echo "Error: PPPoE account and password must be provided when PPPoE is enabled!"
              exit 1
            fi
          fi

      - name: Add other packages
        run: |
          mkdir -p "${{ github.workspace }}/packages"
          cd ${{ github.workspace }}/packages
          if [[ "${{ github.event.inputs.include_others }}" == "yes" ]]; then
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-app-poweroffdevice_1-4_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-i18n-poweroffdevice-zh-cn_1-4_all.ipk
            # wget https://dl.openwrt.ai/packages-24.10/x86_64/kiddin9/luci-app-poweroffdevice_26.057.44252~a27aeb1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocks-libev-ss-local_3.3.5-r13_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocks-libev-ss-redir_3.3.5-r13_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocks-libev-ss-server_3.3.5-r13_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocks-rust-sslocal_1.22.0-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocks-rust-ssserver_1.22.0-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocksr-libev-ssr-local_2.5.6-r11_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocksr-libev-ssr-redir_2.5.6-r11_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/shadowsocksr-libev-ssr-server_2.5.6-r11_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/simple-obfs_0.0.5-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/tcping_0.3-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/trojan-plus_10.0.3-r2_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/tuic-client_1.0.0-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/v2ray-geoip_202502050123.1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/v2ray-geoip_2025.03.08-r1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/v2ray-geosite_20250302153845.1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/v2ray-geosite_2025.03.08-r1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/v2dat_2022.12.15.47b8ee51-r2_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/geoview_0.1.2-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/ipt2socks_1.1.4-r3_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/chinadns-ng_2024.12.22-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/ipt2socks_1.1.4-r3_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/dns2socks_2.1-r2_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/naiveproxy_134.0.6998.39-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/microsocks_1.0.5-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/xray-core_25.3.6-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/xray-plugin_1.8.24-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/sing-box_1.11.4-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-24.10_luci-app-passwall_25.3.9-r1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-24.10_luci-i18n-passwall-zh-cn_25.067.58328.338d2ec_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/nikki_2025.03.10.c0de3c0e-r1_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-app-nikki_1.20.3-r1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-i18n-nikki-zh-cn_25.069.51345.f77c1f0_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/mosdns_5.3.3-r4_x86_64.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-app-mosdns_1.6.11-r1_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-i18n-mosdns-zh-cn_25.061.23891.2523534_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-app-adguardhome_26.073.73112_cf74332_all.ipk
            wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/luci-app-openclash_0.46.079_all.ipk
            wget https://dl.openwrt.ai/packages-24.10/x86_64/kiddin9/luci-app-autotimeset_26.071.56495~ba3444f_all.ipk
          fi

      - name: Add AdGuardHome core
        run: |
          mkdir -p "${{ github.workspace }}/files/usr/bin"
          cd ${{ github.workspace }}/files/usr/bin
          wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/AdGuardHome
          chmod +x AdGuardHome

      - name: Add OpenClash core
        run: |
          mkdir -p "${{ github.workspace }}/files/etc/openclash/core"
          cd ${{ github.workspace }}/files/etc/openclash/core
          wget https://github.com/liuweilhy/OpenwrtPackages/releases/download/24.10-x86-64-20250315/clash_meta
          chmod +x clash_meta

      - name: Build ImmortalWrt-x86-64-efi
        run: |
          partsize="${{ github.event.inputs.partsize }}"
          include_docker="${{ github.event.inputs.include_docker }}"
          include_others="${{ github.event.inputs.include_others }}"
          enable_pppoe="${{ github.event.inputs.enable_pppoe }}"
          pppoe_account="${{ github.event.inputs.pppoe_account }}"
          pppoe_password="${{ github.event.inputs.pppoe_password }}"

          imagename=""
          if [[ "$include_docker" == "yes" ]]; then
            if [[ "$include_others" == "yes" ]]; then
              imagename="docker-plus"
            else
              imagename="docker"
            fi
          else
            if [[ "$include_others" == "yes" ]]; then
              imagename="plus"
            else
              imagename="lite"
            fi
          fi
          
          echo "Building ImmortalWrt-x86-64-efi"
          docker pull immortalwrt/imagebuilder:x86-64-openwrt-24.10.0
          docker run --rm -i \
            --user root \
            -v "${{ github.workspace }}/bin:/home/build/immortalwrt/bin" \
            -v "${{ github.workspace }}/files:/home/build/immortalwrt/files" \
            -v "${{ github.workspace }}/packages:/home/build/immortalwrt/packages" \
            -v "${{ github.workspace }}/x86-64/imm.config:/home/build/immortalwrt/.config" \
            -v "${{ github.workspace }}/x86-64/24.10/build.sh:/home/build/immortalwrt/build.sh" \
            -e IMAGENAME=$imagename \
            -e PARTSIZE=$partsize \
            -e INCLUDE_DOCKER=$include_docker \
            -e INCLUDE_OTHERS=$include_others \
            -e ENABLE_PPPOE=$enable_pppoe \
            -e PPPOE_ACCOUNT=$pppoe_account \
            -e PPPOE_PASSWORD=$pppoe_password \
            immortalwrt/imagebuilder:x86-64-openwrt-24.10.0 /bin/bash /home/build/immortalwrt/build.sh

      - name: Generate Firmware SHA-256
        run: |
          cp ${{ github.workspace }}/bin/targets/x86/64/*squashfs-combined-efi.img.gz ${{ github.workspace }}
          for file in *squashfs-combined-efi.img.gz; do
            sha256sum "$file" > "$file.sha256"
            sha256sum -c "$file.sha256"
          done

      - name: Upload ImmortWrt as release assets
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: v1.0
          body_path: ${{ github.workspace }}/info.md
          files: |
            ${{ github.workspace }}/*squashfs-combined-efi.img.gz
            ${{ github.workspace }}/*.sha256
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
